// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRqAKDVTagMua6-ZzmVnO6zDSKVVKuK6Y',
    appId: '1:374967467307:web:5b925057cd3d53efea996e',
    messagingSenderId: '374967467307',
    projectId: 'word-and-learn',
    authDomain: 'word-and-learn.firebaseapp.com',
    storageBucket: 'word-and-learn.appspot.com',
    measurementId: 'G-64G6XJ8R3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4o13zTqPKPyU27WEZ9wsGwxPz-4_lk44',
    appId: '1:374967467307:android:26c51bdc1afabad3ea996e',
    messagingSenderId: '374967467307',
    projectId: 'word-and-learn',
    storageBucket: 'word-and-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmL4u_c-FwTorry_5NROE1SvmE-bSlVaU',
    appId: '1:374967467307:ios:b6d9c3b35bb8145bea996e',
    messagingSenderId: '374967467307',
    projectId: 'word-and-learn',
    storageBucket: 'word-and-learn.appspot.com',
    iosBundleId: 'com.example.wordAndLearn',
  );
}
