name: Deploy Web Version
on:
  push:
    branches:
      - web
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup & Build Flutter
        uses: cedvdb/action-flutter-build-web@v1
        with:
          build-cmd: flutter build web --release
          working-directory: ./

      - name: Create an artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/*
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: webbuild

      - name: Deploy to artifact to web server using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          key: ${{ secrets.SCP_KEY }}
          port: ${{ secrets.SCP_PORT }}
          source: webbuild/*
          target: ${{ secrets.SCP_TARGET }}
